/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_durip_app_DeviceSwitch */

#ifndef _Included_it_durip_app_DeviceSwitch
#define _Included_it_durip_app_DeviceSwitch
#ifdef __cplusplus
extern "C" {
#endif
#undef it_durip_app_DeviceSwitch_AUTO_HIDE
#define it_durip_app_DeviceSwitch_AUTO_HIDE 1L
#undef it_durip_app_DeviceSwitch_AUTO_HIDE_DELAY_MILLIS
#define it_durip_app_DeviceSwitch_AUTO_HIDE_DELAY_MILLIS 3000L
#undef it_durip_app_DeviceSwitch_TOGGLE_ON_CLICK
#define it_durip_app_DeviceSwitch_TOGGLE_ON_CLICK 1L
#undef it_durip_app_DeviceSwitch_HIDER_FLAGS
#define it_durip_app_DeviceSwitch_HIDER_FLAGS 6L
/*
 * Class:     it_durip_app_DeviceSwitch
 * Method:    activeHosts
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_it_durip_1app_DeviceSwitch_activeHosts
  (JNIEnv *, jobject, jint);

/*
 * Class:     it_durip_app_DeviceSwitch
 * Method:    unactiveHosts
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_it_durip_1app_DeviceSwitch_unactiveHosts
  (JNIEnv *, jobject, jint);

/*
 * Class:     it_durip_app_DeviceSwitch
 * Method:    hostOn
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_it_durip_1app_DeviceSwitch_hostOn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     it_durip_app_DeviceSwitch
 * Method:    hostOff
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_it_durip_1app_DeviceSwitch_hostOff
  (JNIEnv *, jobject, jstring);

/*
 * Class:     it_durip_app_DeviceSwitch
 * Method:    flush
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_it_durip_1app_DeviceSwitch_flush
  (JNIEnv *, jobject);

/*
 * Class:     it_durip_app_DeviceSwitch
 * Method:    fill
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_it_durip_1app_DeviceSwitch_fill
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
