/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_durip_app_Olsr */

#ifndef _Included_it_durip_app_Olsr
#define _Included_it_durip_app_Olsr
//#define _Included_it_durip_app_olsrdLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_durip_app_Olsr
 * Method:    olsrdOff
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_it_durip_1app_Olsr_olsrdOff
(JNIEnv *, jobject, jint);

//JNIEXPORT jint JNICALL Java_it_durip_1app_Olsr_olsrdLogOff
//  (JNIEnv *, jobject, jint);

/*
 * Class:     it_durip_app_Olsr
 * Method:    olsrdOn
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_it_durip_1app_Olsr_olsrdOn
  (JNIEnv *, jobject, jint);

//JNIEXPORT jint JNICALL Java_it_durip_1app_Olsr_olsrdLogOn
//  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
