/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_durip_app_Hosts */

#ifndef _Included_it_durip_app_Hosts
#define _Included_it_durip_app_Hosts
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_durip_app_Hosts
 * Method:    activeHosts
 * Signature: (I)I
 */
JNIEXPORT jobjectArray JNICALL Java_it_durip_1app_Hosts_activeHosts
  (JNIEnv *, jobject, jint);

/*
 * Class:     it_durip_app_Hosts
 * Method:    unactiveHosts
 * Signature: (I)I
 */
JNIEXPORT jobjectArray JNICALL Java_it_durip_1app_Hosts_unactiveHosts
  (JNIEnv *, jobject, jint);

/*
 * Class:     it_durip_app_Hosts
 * Method:    hostOn
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_it_durip_1app_Hosts_hostOn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     it_durip_app_Hosts
 * Method:    hostOff
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_it_durip_1app_Hosts_hostOff
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
